import { GetServerSideProps } from "next";
import Head from "next/head";
import NavBar from "../lib/Navbar";
import type { NextPage } from "next";
import axios from "axios";

interface Props {
  navUrls: {
    urls: string[];
  };
}

const Home: NextPage<Props> = ({ navUrls }) => {
  return (
    <div>
      <Head>
        <title>Chispita Challange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar navUrls={navUrls}></NavBar>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const emptyUrls: { urls: Array<string> } = { urls: [""] };

  //url from page/api
  try {
    const resUrls = await axios(`http://localhost:3000/api/nav`);
    const navUrls = await resUrls.data;

    return {
      props: { navUrls },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: { emptyUrls },
  };
};

export default Home;
